### ISSUE TITLE
Implement D/O/Name

### ISSUE THREAD

**Issue by iamalnewkirk** [iamalnewkirk/do#211]
## Issue

We need a class to represent the concept of a name (i.e. namespace) and provide common methods for operating on a name, e.g. converting to and from a filename.

## Solution

Create a D/O/Name class to provide a consistent set of behaviors for operating on a name. Or, add this additional behavior to D/O/Space.

```
  my $foo = Data::Object::Name->new('Foo::Bar');

  $foo->id # Foo_Bar
  $foo->filename # foo_bar
```

## Todo

- [ ] Initial implementation
- [ ] Port method class_file from Export
- [ ] Port method class_name from Export
- [ ] Port method class_path from Export
- [ ] Port method path_class from Export
- [ ] Port method path_name from Export
