### ISSUE TITLE
Draft Prototype Arch

### ISSUE THREAD

**Issue by iamalnewkirk** [iamalnewkirk/do#213]
## Issue

We need a way to create classes, roles, rules, types, etc, in-memory without much ceremony.

## Solution

Start drafting the models and architecture to support prototype-based programming.

## Todo

- [ ] Handle Prototype Declaration
- [ ] Handle Routine Declaration
- [ ] Handle Role Declaration
- [ ] Handle Require Declaration
- [ ] Handle Parent Declaration
- [ ] Handle Package Declaration
- [ ] Handle Method Declaration
- [ ] Handle Instance Declaration
- [ ] Handle Import Declaration
- [ ] Handle Function Declaration
