### ISSUE TITLE
Cleanup Core Roles

### ISSUE THREAD

**Issue by iamalnewkirk** [iamalnewkirk/do#262]
## Issue

Some of the core roles are no longer necessary, some should be renamed, some removed.

## Solution

Clean-up core roles and make sure they can be applied using `Do` and `Data::Object` import statements.

E.g.

```
  package Foo;

  use Do 'Class';

  use Do 'WithThrowable';
  use Do 'WithCatchable';
  use Do 'WithImmutable';

  1;
```

## Todo

- [x] Drop Detract
- [x] Merge Output and Dumper
- [x] Functable Ignored from Import
- [x] Drop Catchable
- [x] Add Roles to Library
